# Pandas数据结构

In [1]:
import pandas as pd

* Series

In [2]:
# 通过list构建Series  #重点
ser_obj = pd.Series(range(10, 20))
print(type(ser_obj))

<class 'pandas.core.series.Series'>


In [3]:
# 获取数据
print(ser_obj.values)

# 获取索引
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)


In [4]:
# 预览数据
print(ser_obj.head(3))

0    10
1    11
2    12
dtype: int64


In [5]:
print(ser_obj)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [6]:
#通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

10
18


In [7]:
# 索引与数据的对应关系仍保持在数组运算的结果中 #重点
print(ser_obj * 2)
print(ser_obj > 15)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [17]:
print(ser_obj[ser_obj>15]) #重点

6    16
7    17
8    18
9    19
dtype: int64


In [8]:
# 通过dict构建Series  #重点
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)

2001    17.8
2002    20.1
2003    16.5
dtype: float64
Int64Index([2001, 2002, 2003], dtype='int64')


In [9]:
# name属性  #重点
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print(ser_obj2.head())

year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


* DataFrame

In [10]:
import numpy as np

# 通过ndarray构建DataFrame
array = np.random.randn(5,4)
print(array)

df_obj = pd.DataFrame(array) #重点
print(df_obj.head())

[[ 0.14693507 -0.35307032  0.53501847 -0.22095991]
 [-0.91779189 -1.19421198  0.43250572 -0.71782458]
 [ 2.16894615 -0.83515961  0.4780367   0.18765656]
 [ 1.35484974  1.52671507  1.38766144  0.90275215]
 [-0.12970782 -0.06204032 -0.92091251 -1.88246492]]
          0         1         2         3
0  0.146935 -0.353070  0.535018 -0.220960
1 -0.917792 -1.194212  0.432506 -0.717825
2  2.168946 -0.835160  0.478037  0.187657
3  1.354850  1.526715  1.387661  0.902752
4 -0.129708 -0.062040 -0.920913 -1.882465


In [11]:
# 通过dict构建DataFrame  #重点 key 代表着列的名称
dict_data = {'A': 1., 
             'B': pd.Timestamp('20161217'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E' : pd.Categorical(["Python","Java","C++","C#"]),
             'F' : 'ChinaHadoop' }
#print dict_data
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2.head())

     A          B    C  D       E            F
0  1.0 2016-12-17  1.0  3  Python  ChinaHadoop
1  1.0 2016-12-17  1.0  3    Java  ChinaHadoop
2  1.0 2016-12-17  1.0  3     C++  ChinaHadoop
3  1.0 2016-12-17  1.0  3      C#  ChinaHadoop


In [19]:
# 通过  列   索引获取列数据
print(df_obj2['A']) #推荐这肿
print('--------')
print(type(df_obj2['A']))
print('--------')
print(df_obj2.A)

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64
--------
<class 'pandas.core.series.Series'>
--------
0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64


In [13]:
# 增加列           #重点
df_obj2['G'] = df_obj2['D'] + 4 
print(df_obj2.head())

     A          B    C  D       E            F  G
0  1.0 2016-12-17  1.0  3  Python  ChinaHadoop  7
1  1.0 2016-12-17  1.0  3    Java  ChinaHadoop  7
2  1.0 2016-12-17  1.0  3     C++  ChinaHadoop  7
3  1.0 2016-12-17  1.0  3      C#  ChinaHadoop  7


In [14]:
# 删除列       #重点
del(df_obj2['G'] )
print(df_obj2.head())

     A          B    C  D       E            F
0  1.0 2016-12-17  1.0  3  Python  ChinaHadoop
1  1.0 2016-12-17  1.0  3    Java  ChinaHadoop
2  1.0 2016-12-17  1.0  3     C++  ChinaHadoop
3  1.0 2016-12-17  1.0  3      C#  ChinaHadoop


* 索引对象 Index

In [15]:
print(type(ser_obj.index))

print(type(df_obj2.index))

print(df_obj2.index)

<class 'pandas.indexes.range.RangeIndex'>
<class 'pandas.indexes.numeric.Int64Index'>
Int64Index([0, 1, 2, 3], dtype='int64')


In [16]:
# 索引对象不可变
df_obj2.index[0] = 2

TypeError: Index does not support mutable operations