# 数据合并 concat

In [1]:
import numpy as np
import pandas as pd

* NumPy的concat

In [2]:
arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))

print arr1
print arr2

[[3 9 7 6]
 [4 6 9 9]
 [1 8 8 5]]
[[2 7 2 8]
 [9 8 0 6]
 [9 1 4 8]]


In [5]:
np.concatenate([arr1, arr2])

array([[3, 9, 7, 6],
       [4, 6, 9, 9],
       [1, 8, 8, 5],
       [2, 7, 2, 8],
       [9, 8, 0, 6],
       [9, 1, 4, 8]])

In [6]:
np.concatenate([arr1, arr2], axis=1)

array([[3, 9, 7, 6, 2, 7, 2, 8],
       [4, 6, 9, 9, 9, 8, 0, 6],
       [1, 8, 8, 5, 9, 1, 4, 8]])

* Series上的concat

In [10]:
# index 没有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(0,5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(5,9))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(9,12))

print ser_obj1
print ser_obj2
print ser_obj3

0    2
1    5
2    9
3    1
4    6
dtype: int32
5    1
6    8
7    1
8    6
dtype: int32
9     8
10    5
11    0
dtype: int32


In [19]:
pd.concat([ser_obj1, ser_obj2, ser_obj3])

0     2
1     5
2     9
3     1
4     6
5     1
6     8
7     1
8     6
9     8
10    5
11    0
dtype: int32

In [17]:
pd.concat([ser_obj1, ser_obj2, ser_obj3], axis=1)

0    1    2
0   2.0  NaN  NaN
1   5.0  NaN  NaN
2   9.0  NaN  NaN
3   1.0  NaN  NaN
4   6.0  NaN  NaN
5   NaN  1.0  NaN
6   NaN  8.0  NaN
7   NaN  1.0  NaN
8   NaN  6.0  NaN
9   NaN  NaN  8.0
10  NaN  NaN  5.0
11  NaN  NaN  0.0

In [20]:
# index 有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(4))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(3))

print ser_obj1
print ser_obj2
print ser_obj3

0    9
1    2
2    5
3    7
4    1
dtype: int32
0    4
1    9
2    9
3    3
dtype: int32
0    4
1    8
2    8
dtype: int32


In [22]:
pd.concat([ser_obj1, ser_obj2, ser_obj3])

0    9
1    2
2    5
3    7
4    1
0    4
1    9
2    9
3    3
0    4
1    8
2    8
dtype: int32

In [24]:
pd.concat([ser_obj1, ser_obj2, ser_obj3], axis=1, join='inner')

0  1  2
0  9  4  4
1  2  9  8
2  5  9  8

* DataFrame上的concat

In [34]:
df_obj1 = pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df_obj2 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['C', 'D'])
print df_obj1
print df_obj2

   A  B
a  8  4
b  0  6
c  4  9
   C  D
a  9  2
b  1  6


In [35]:
pd.concat([df_obj1, df_obj2])

A    B    C    D
a  8.0  4.0  NaN  NaN
b  0.0  6.0  NaN  NaN
c  4.0  9.0  NaN  NaN
a  NaN  NaN  9.0  2.0
b  NaN  NaN  1.0  6.0

In [36]:
pd.concat([df_obj1, df_obj2], axis=1)

A  B    C    D
a  8  4  9.0  2.0
b  0  6  1.0  6.0
c  4  9  NaN  NaN